---
- name: Create bitbucket.org/eviljonny directory
  ansible.builtin.file:
    path: /home/eviljonny/gitdevel/bitbucket.org/eviljonny/bashconfig
    state: directory
    owner: eviljonny
    group: eviljonny
    mode: 0700
  
- name: Checkout bashconfig repo
  ansible.builtin.git:
    repo: git@bitbucket.org:eviljonny/bashconfig.git
    dest: /home/eviljonny/gitdevel/bitbucket.org/eviljonny/bashconfig/
    accept_hostkey: true
    force: false
    update: false

- name: Symlink bashrc to git dir
  ansible.builtin.file:
    src: /home/eviljonny/gitdevel/bitbucket.org/eviljonny/bashconfig/bashrc
    dest: /home/eviljonny/.bashrc
    owner: eviljonny
    group: eviljonny
    state: link
    force: true

- name: Create bashrc.d directory
  ansible.builtin.file:
    path: /home/eviljonny/.bashrc.d/
    state: directory
    owner: eviljonny
    group: eviljonny
    mode: 0700

- name: Reset connection
  ansible.builtin.meta: reset_connection
