---
- name: "Install Common Tools"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - p7zip
    - pwgen
    - rename
    - silversearcher-ag
    - tree
    - unrar

- name: Install additional packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ additional_packages }}"
