---
- name: Install ag
  become: true
  ansible.builtin.apt:
    name: silversearcher-ag
    state: present

- name: Install tree
  become: true
  ansible.builtin.apt:
    name: tree
    state: present
