---
- name: Install ag
  become: true
  ansible.builtin.apt:
    name: silversearcher-ag
    state: present

- name: Install tree
  become: true
  ansible.builtin.apt:
    name: tree
    state: present

- name: Install 7zip
  become: true
  ansible.builtin.apt:
    name: 7zip
    state: present

- name: Install rar
  become: true
  ansible.builtin.apt:
    name: rar
    state: present
