---
- name: Check to see if helm keyring is installed
  ansible.builtin.stat:
    path: /etc/apt/keyrings/helm-apt-keyring.gpg
  register: helm_keyring_stat

- name: Ensure keyrings directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    mode: '0755'
    state: directory
    owner: root
    group: root

- name: Copy helm keyring key
  become: true
  ansible.builtin.get_url:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    dest: /etc/apt/keyrings/helm-apt-keyring.asc
    mode: "0644"
  register: helm_keyring

- name: Verify helm GPG key id
  ansible.builtin.shell: >-
    set -euo pipefail;
    test $(
      gpg --show-keys --with-colons /etc/apt/keyrings/helm-apt-keyring.asc |
      awk -F: '$1 == "fpr" {print $10}' |
      head -n 1
    ) == "DDF78C3E6EBB2D2CC223C95C62BA89D07698DBC6"
  args:
    executable: /bin/bash
  changed_when: false

  # This can be removed once it's been applied everywhere
- name: Remove old unarmoured helm keyring and repo list
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/keyrings/helm-apt-keyring.gpg
    - /etc/apt/sources.list.d/helm.list

- name: Add helm deb822 repository
  become: true
  ansible.builtin.deb822_repository:
    name: helm
    types: deb
    uris: https://packages.buildkite.com/helm-linux/helm-debian/any/
    suites: any
    components:
      - main
    signed_by: /etc/apt/keyrings/helm-apt-keyring.asc

- name: Install helm
  become: true
  ansible.builtin.apt:
    name:
      - helm
    update_cache: true
    state: present
