---
- name: Check to see if helm keyring is installed
  ansible.builtin.stat:
    path: /etc/apt/keyrings/helm-apt-keyring.gpg
  register: helm_keyring_stat

- name: Ensure keyrings directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    mode: '0755'
    state: directory
    owner: root
    group: root

- name: Copy helm keyring key
  become: true
  ansible.builtin.get_url:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    dest: /etc/apt/keyrings/helm-apt-keyring.asc
  register: helm_keyring

- name: Verify helm GPG key id
  ansible.builtin.shell: |
    test $(gpg --show-keys --with-colons /etc/apt/keyrings/helm-apt-keyring.asc | awk -F: '$1 == "fpr" {print $10}' | head -n 1) == "DDF78C3E6EBB2D2CC223C95C62BA89D07698DBC6"
  args:
    executable: /bin/bash
  changed_when: false

- name: Dearmour ansible keyring key
  when: helm_keyring.changed or not helm_keyring_stat.stat.exists 
  become: true
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/helm-apt-keyring.gpg /etc/apt/keyrings/helm-apt-keyring.asc

- name: Change permissions on helm keyring key
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/helm-apt-keyring.gpg
    owner: root
    group: root
    mode: '0644'

- name: Add helm repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/helm-apt-keyring.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
    state: present
    filename: helm

- name: Install helm
  become: true
  ansible.builtin.apt:
    name:
      - helm
    update_cache: yes
    state: present
