---
- hosts: local
  roles:
    - eviljonny-user
    - role: gitdevel-setup
      vars:
        install_visual_git_tools: true
    - bash-config
    - role: asdf-setup
      vars:
        plugins_to_install:
          - nodejs
          - shellcheck
        tool_versions:
          nodejs: "22.14.0"
          shellcheck: "0.10.0"
    - validate-local-configured 
    - vim-config
    - role: common-tools
      vars:
        additional_packages:
          - vinagre
    - apple-hardware
    - common-desktop
    - home-nfs-client

- hosts: k8s-1
  tasks:
    - include_role:
        name: kubectl
        tasks_from: gather_config_vars

- hosts: local
  roles:
    - kubectl
