---
- hosts: k8s_control_nodes 
  roles:
    - eviljonny-user
    - gitdevel-setup
    - bash-config
    - asdf-setup
    - role: vim-config
      vars:
        remove_vim_instant_markdown: true
    - common-tools
    - k3s

- hosts: k8s_agents
  roles:
    - k3s-agent
