---
- hosts: local
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  roles:
    - eviljonny-user
    - role: gitdevel-setup
      vars:
        install_visual_git_tools: true
    - bash-config
    - role: asdf-setup
      vars:
        plugins_to_install:
          - nodejs
          - shellcheck
        tool_versions:
          nodejs: "22.14.0"
          shellcheck: "0.10.0"
    - validate-local-configured 
    - vim-config
    - common-tools
    - apple-hardware
    - common-desktop
