---
- name: Install Local Laptop for fun dev
  hosts: local
  roles:
    - eviljonny-user
    - role: gitdevel-setup
      vars:
        install_visual_git_tools: true
    - role: vim-config
      vars:
        remove_vim_instant_markdown: true
    - bash-config
    - role: common-tools
      vars:
        additional_packages:
          - bash-completion
          - cowsay
          - dos2unix
          - gnupg
          - jq
          - libbz2-dev
          - libffi-dev
          - liblzma-dev
          - libncurses-dev
          - libreadline-dev
          - libsqlite3-dev
          - libyaml-dev
          - parallel
          - pre-commit
          - v4l-utils
          - vinagre
          - yq
    - role: asdf-setup
      vars:
        plugins_to_install:
          - nodejs
          - python
          - ruby
          - shellcheck
          - terraform
          - terraform-docs
        plugins_to_install_by_url:
          golang: "https://github.com/asdf-community/asdf-golang.git"
        tool_versions:
          golang: "1.27.1"
          nodejs: "22.20.0"
          python: "3.14.7"
          ruby: "4.0.6"
          shellcheck: "0.11.0"
          terraform: "1.16.1"
          "terraform-docs": "v0.24.0"
    - validate-local-configured
    - apple-hardware
    - common-desktop
    - home-nfs-client
    - docker
    - helm

- name: Get the config vars from the k8s cluster
  hosts: k8s-1
  tasks:
    - name: Gather vars needed for kubectl setup
      ansible.builtin.include_role:
        name: kubectl
        tasks_from: gather_config_vars

- name: Install and configure local kubectl
  hosts: local
  roles:
    - kubectl
