---
plugins_to_install:
  - nodejs
plugins_to_install_by_url:
  golang: "https://github.com/asdf-community/asdf-golang.git"
tool_versions:
  golang: "1.27.1"
  nodejs: "22.20.0"
asdf_update_plugins: false
