---
- name: Install asdf executable
  ansible.builtin.include_role:
    name: install_github_release
    public: false
  vars:
    install_github_release_source_github_repo: asdf-vm/asdf
    install_github_release_source_release_file_prefix: "asdf"
    install_github_release_source_release_file_separator: "-"
    install_github_release_source_release_file_extension: ".tar.gz"

    install_github_release_target_location_directory: /home/eviljonny/bin
    install_github_release_target_executable_name: asdf

    install_github_release_version_line_match_regex: "^asdf version v"
    install_github_release_version_line_replace_regex:
      's/^asdf version v([^ ]+) .*$/\1/'

    install_github_release_architecture:
      x86_64: "amd64"
      aarch64: "arm64"

- name: Create bashrc.d asdf integration
  ansible.builtin.copy:
    dest: /home/eviljonny/.bashrc.d/00-asdf.bashrc
    content: |
      #!/usr/bin/env bash
      export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
      . <(asdf completion bash)
    mode: '0664'

- name: Reset connection
  ansible.builtin.meta: reset_connection

- name: Ensure .asdfrc exists
  ansible.builtin.file:
    path: /home/eviljonny/.asdfrc
    state: touch
    mode: '0664'
    access_time: preserve
    modification_time: preserve

- name: Enable legacy_version_file
  ansible.builtin.lineinfile:
    path: /home/eviljonny/.asdfrc
    regexp: '^legacy_version_file'
    line: legacy_version_file = yes

- name: Get installed plugins
  ansible.builtin.command: >-
    cmd: /home/eviljonny/bin/asdf plugin list
  changed_when: false
  register: asdf_installed_plugins

- name: Add asdf plugins
  when: item not in asdf_installed_plugins.stdout_lines
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: 'source /home/eviljonny/.bashrc && asdf plugin add {{ item | quote }}'
  loop: "{{ plugins_to_install }}"
  changed_when: item not in asdf_installed_plugins.stdout_lines

- name: Add asdf plugins by url
  when: item.key not in asdf_installed_plugins.stdout_lines
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: >-
      source /home/eviljonny/.bashrc
      && asdf plugin add {{ item.key | quote }} {{ item.value | quote }}'
  loop: "{{ plugins_to_install_by_url | dict2items }}"
  changed_when: item not in asdf_installed_plugins.stdout_lines

- name: Ensure .tool-versions exists
  ansible.builtin.file:
    path: /home/eviljonny/.tool-versions
    state: touch
    mode: '0664'
    access_time: preserve
    modification_time: preserve

- name: Add to tool-versions file
  ansible.builtin.lineinfile:
    path: /home/eviljonny/.tool-versions
    regexp: '^{{ item.key }} '
    line: '{{ item.key }} {{ item.value }}'
  loop: "{{ tool_versions | dict2items }}"

- name: Trigger asdf install when updating plugins
  when: asdf_update_plugins
  ansible.builtin.assert:
    that: true
    quiet: true
  changed_when: true
  notify:
    - Update asdf plugins

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Reset connection
  ansible.builtin.meta: reset_connection

- name: Run asdf install
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: "source /home/eviljonny/.bashrc && asdf install {{ item.key }}"
  register: asdf_install_result
  changed_when: asdf_install_result is search("Installing")
  loop: "{{ tool_versions | dict2items }}"
