---
- name: Ensure keyrings directory exists
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    mode: '0755'
    state: directory
    owner: root
    group: root

- name: Copy kubernetes keyring key
  become: true
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/{{ k3s_version }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.key
    mode: "0644"
  vars:
    k3s_version: "{{ hostvars['k8s-1']['kubectl_k3s_major_minor_version'] }}"

# This can be removed once it's been applied everywhere
- name: Remove old unarmoured helm keyring and repo list
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    - /etc/apt/sources.list.d/kubernetes.list

- name: Add k8s deb822 repository
  become: true
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: deb
    uris: https://pkgs.k8s.io/core:/stable:/{{ k3s_version }}/deb/
    suites: "/"
    signed_by: /etc/apt/keyrings/kubernetes-apt-keyring.key
  vars:
    k3s_version: "{{ hostvars['k8s-1']['kubectl_k3s_major_minor_version'] }}"

- name: Install kubectl
  become: true
  ansible.builtin.apt:
    name:
      - kubectl
    update_cache: true
    state: present

- name: Ensure kube dir
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    owner: eviljonny
    group: eviljonny
    mode: '0700'

- name: Write kubectl config file
  ansible.builtin.template:
    src: kubeconfig.yml
    dest: $HOME/.kube/pik8s.yaml
    owner: eviljonny
    group: eviljonny
    mode: '0600'
  vars:
    cluster_certificate_authority_data: >-
      {{
        (
          hostvars['k8s-1']['kubectl_remote_k3s_config'].content
          | b64decode
          | from_yaml
        )['clusters'][0]['cluster']['certificate-authority-data']
      }}
    client_certificate_data: >-
      {{
        (
          hostvars['k8s-1']['kubectl_remote_k3s_config'].content
          | b64decode
          | from_yaml
        )['users'][0]['user']['client-certificate-data']
      }}
    client_key_data: >-
      {{
        (
          hostvars['k8s-1']['kubectl_remote_k3s_config'].content
          | b64decode
          |  from_yaml
        )['users'][0]['user']['client-key-data']
      }}

- name: Copy pik8s kubeconfig file
  ansible.builtin.copy:
    src: "pik8s.sh"
    dest: "$HOME/.kube/pik8s.sh"
    owner: eviljonny
    group: eviljonny
    mode: "0600"
