---
- name: install plain vim
  when: force_plain_vim or ansible_distribution_version == "20.04"
  block:
    - name: Create bitbucket.org/eviljonny/vimconfig directory
      ansible.builtin.file:
        path: /home/eviljonny/gitdevel/bitbucket.org/eviljonny/vimconfig
        state: directory
        owner: eviljonny
        group: eviljonny
        mode: 0700

    - name: Symlink .vim to git dir
      ansible.builtin.file:
        src: /home/eviljonny/gitdevel/bitbucket.org/eviljonny/vimconfig/
        dest: /home/eviljonny/.vim
        owner: eviljonny
        group: eviljonny
        state: link
        force: true

    - name: Checkout vimconfig repo
      ansible.builtin.git:
        repo: git@bitbucket.org:eviljonny/vimconfig.git
        dest: /home/eviljonny/gitdevel/bitbucket.org/eviljonny/vimconfig/
        accept_hostkey: true
        force: false
        update: false
        version: migrate-to-coc

    - name: vim is installed
      become: true
      ansible.builtin.apt:
        name: vim
        state: present

    - name: ctags is installed
      become: true
      ansible.builtin.apt:
        name: exuberant-ctags
        state: present

    - name: Disable vim-instant-markdown
      when: remove_vim_instant_markdown
      block:
        - name: Comment out Plug install
          ansible.builtin.replace:
            path: /home/eviljonny/gitdevel/bitbucket.org/eviljonny/vimconfig/vimrc
            regexp: "^(Plug 'instant-markdown/vim-instant-markdown.*)$"
            replace: '" \1'

        - name: Ensure vim-instant-markdown dir does not exist
          ansible.builtin.file:
            path: /home/eviljonny/gitdevel/bitbucket.org/eviljonny/vimconfig/plugged/vim-instant-markdown
            state: absent

    - name: Install vim-instant-markdown dependencies
      when: not remove_vim_instant_markdown
      block:
      - name: install linux dependencies
        when: ansible_system == "Linux"
        block:
        - name: Install xdg-utils
          become: true
          ansible.builtin.apt:
            name: xdg-utils
            state: present

        - name: Install curl
          become: true
          ansible.builtin.apt:
            name: curl
            state: present

        - name: Install instant-markdown-d
          community.general.npm:
            executable: /home/eviljonny/.asdf/shims/npm
            name: instant-markdown-d
            global: true

- name: install neovim
  when: not force_plain_vim and ansible_distribution_version != "20.04"
  block:
    - name: Ensure home bin exists
      ansible.builtin.file:
        path: /home/eviljonny/bin
        state: directory
        mode: '0755'

    - name: Create /home/eviljonny/gitdevel/github.com/jfharden/kickstart.nvim/
      ansible.builtin.file:
        path: /home/eviljonny/gitdevel/github.com/jfharden/kickstart.nvim
        state: directory
        owner: eviljonny
        group: eviljonny
        mode: 0700

    - name: Symlink .config/nvim to git dir
      ansible.builtin.file:
        src: /home/eviljonny/gitdevel/github.com/jfharden/kickstart.nvim
        dest: /home/eviljonny/.config/nvim
        owner: eviljonny
        group: eviljonny
        state: link
        force: true

    - name: Checkout kickstart config
      ansible.builtin.git:
        repo: git@github.com:jfharden/kickstart.nvim.git
        dest: /home/eviljonny/gitdevel/github.com/jfharden/kickstart.nvim
        accept_hostkey: true
        force: false
        update: false

    - name: neovim is installed
      block:
        - name: Check if neovim binary exists
          ansible.builtin.stat:
            path: /home/eviljonny/bin/nvim
          register: neovim_binary_stat

        - name: Get current neovim version
          when: neovim_binary_stat.stat.exists
          ansible.builtin.shell:
            executable: /bin/bash
            cmd: '/home/eviljonny/bin/nvim --version | grep "NVIM v" | cut -f 2 -d " " | sed -E "s/^v//"'
          register: neovim_version
          changed_when: false

        - name: Get neovim latest release information
          ansible.builtin.uri:
            url: https://api.github.com/repos/neovim/neovim/releases/latest
            return_content: true
          register: neovim_latest_release_json

        - name: Set neovim facts
          ansible.builtin.set_fact:
            neovim_appimage_name: "{{ neovim_release_json.name }}"
            neovim_zip_url: "{{ neovim_release_json.browser_download_url }}"
            neovim_latest_version: "{{ neovim_parsed_release_json.tag_name }}"
            neovim_latest_version_without_prefix: "{{ neovim_parsed_release_json.tag_name | regex_replace('^v', '') }}"
          vars:
            neovim_binary_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"
            neovim_platform: "{{ ansible_system | lower }}"
            neovim_release_json: "{{ neovim_latest_release_json.json | community.general.json_query('assets[?contains(name, `nvim-' + neovim_platform + '-' + neovim_binary_arch +'`) && ends_with(name, `appimage`)] | [0]') }}"
            neovim_parsed_release_json: "{{ neovim_latest_release_json.json }}"

        - name: Install or update neovim
          when: (not neovim_binary_stat.stat.exists) or neovim_latest_version_without_prefix is version(neovim_version.stdout_lines[0], ">")
          block:
            - name: Download neovim release archive
              ansible.builtin.get_url:
                url: "{{ neovim_zip_url }}"
                dest: "/tmp/{{ neovim_appimage_name }}"

            - name: Copy neovim binary into /home/eviljonny/bin
              ansible.builtin.copy:
                src: "/tmp/{{ neovim_appimage_name }}"
                remote_src: true
                dest: /home/eviljonny/bin/nvim
                mode: "0750"

    - name: neovim kickstart dependencies are installed
      block:
        - name: fd, ripgrep are installed
          become: true
          ansible.builtin.apt:
            name:
              - fd-find
              - ripgrep
            state: present

    - name: tree-sitter-cli is installed
      block:
        - name: Check if tree-sitter-cli binary exists
          ansible.builtin.stat:
            path: /home/eviljonny/bin/tree-sitter
          register: tree_sitter_cli_binary_stat

        - name: Get current tree-sitter-cli version
          when: tree_sitter_cli_binary_stat.stat.exists
          ansible.builtin.shell:
            executable: /bin/bash
            cmd: '/home/eviljonny/bin/tree-sitter --version | head -n 1 | cut -f 2 -d " "'
          register: tree_sitter_cli_version
          changed_when: false

        - name: Get tree-sitter-cli latest release information
          ansible.builtin.uri:
            url: https://api.github.com/repos/tree-sitter/tree-sitter/releases/latest
            return_content: true
          register: tree_sitter_cli_latest_release_json

        - name: Set tree_sitter_cli facts
          ansible.builtin.set_fact:
            tree_sitter_cli_zip_name: "{{ tree_sitter_cli_release_json.name }}"
            tree_sitter_cli_zip_url: "{{ tree_sitter_cli_release_json.browser_download_url }}"
            tree_sitter_cli_latest_version: "{{ tree_sitter_cli_parsed_release_json.tag_name }}"
            tree_sitter_cli_latest_version_without_prefix: "{{ tree_sitter_cli_parsed_release_json.tag_name | regex_replace('^v', '') }}"
          vars:
            tree_sitter_cli_binary_arch: "{{ 'x64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"
            tree_sitter_cli_platform: "{{ ansible_system | lower }}"
            tree_sitter_cli_release_json: "{{ tree_sitter_cli_latest_release_json.json | community.general.json_query('assets[?contains(name, `tree-sitter-cli-' + tree_sitter_cli_platform + '-' + tree_sitter_cli_binary_arch +'`) && ends_with(name, `zip`)] | [0]') }}"
            tree_sitter_cli_parsed_release_json: "{{ tree_sitter_cli_latest_release_json.json }}"

        - name: Install or update tree-sitter-cli
          when: (not tree_sitter_cli_binary_stat.stat.exists) or tree_sitter_cli_latest_version_without_prefix is version(tree_sitter_cli_version.stdout_lines[0], ">")
          block:
            - name: Download tree_sitter_cli release archive
              ansible.builtin.get_url:
                url: "{{ tree_sitter_cli_zip_url }}"
                dest: "/tmp/{{ tree_sitter_cli_zip_name }}"

            - name: Copy tree_sitter_cli binary into homedir
              ansible.builtin.unarchive:
                src: "/tmp/{{ tree_sitter_cli_zip_name }}"
                remote_src: true
                dest: /home/eviljonny/bin/
