---
- name: Ensure borgbackup config dir exists
  become: true
  ansible.builtin.file:
    path: /root/borgbackup
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Stat passphrase file
  become: true
  ansible.builtin.stat:
    path: /root/borgbackup/passphrase
  register: passphrase_stat

- name: Fail if passphrase file doesn't exist
  ansible.builtin.fail:
    msg: The passphrase file /root/borgbackup/passphrase does not exist. You need to create it containing the passphrase used for the borgbackup repokey
  when: not passphrase_stat.stat.exists

- name: Ensure correct permissions for passphrase
  become: true
  ansible.builtin.file:
    path: /root/borgbackup/passphrase
    owner: root
    group: root
    mode: "0600"
    state: file

- name: Stat username file
  become: true
  ansible.builtin.stat:
    path: /root/borgbackup/hetzner_username
  register: username_stat

- name: Fail if username file doesn't exist
  ansible.builtin.fail:
    msg: The username file /root/borgbackup/hetzner_username does not exist. You need to create it containing the hetzner username used for the storagebox
  when: not username_stat.stat.exists

- name: Ensure correct permissions for username
  become: true
  ansible.builtin.file:
    path: /root/borgbackup/hetzner_username
    owner: root
    group: root
    mode: "0600"
    state: file

- name: Install borgbackup
  become: true
  ansible.builtin.apt:
    name: borgbackup
    state: present

- name: Copy scripts
  become: true
  ansible.builtin.copy:
    src: "../files/{{ item }}"
    dest: "/root/borgbackup/{{ item }}"
    owner: root
    group: root
    mode: "0700"
  loop:
    - borg_env.sh
    - perform_backup.sh
    - init_repo.sh
    - export_repo_key.sh
    - send_success_notice.sh
    - send_failure_notice.sh

- name: Set up cron to backup daily
  become: true
  ansible.builtin.cron:
    name: Daily borgbackup
    cron_file: /etc/cron.d/borgbackup
    disabled: false
    minute: "0"
    hour: "2"
    day: "*"
    month: "*"
    weekday: "*"
    job: cd /root/borgbackup && ((./perform_backup.sh && ./send_success_notice.sh) || ./send_failure_notice.sh)
    state: present
    user: root
