- name: Ensure docker engine installed
  become: true
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Ensure docker buildx installed
  become: true
  ansible.builtin.apt:
    name: docker-buildx
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Ensure qemu-user-static is installed
  become: true
  ansible.builtin.apt:
    name: qemu-user-static
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Check for presence of docker daemon config
  become: true
  ansible.builtin.stat:
    path: /etc/docker/daemon.json
  register: docker_daemon_json_stat

- name: Copy default daemon config
  become: true
  when: not docker_daemon_json_stat.stat.exists
  ansible.builtin.copy:
    src: "../files/daemon.json"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0600'
  notify:
    - Restart docker daemon

- name: Get qemu arm registration status
  become: true
  ansible.builtin.command:
    cmd: "grep '^flags: .*F.*$' /proc/sys/fs/binfmt_misc/qemu-arm"
  ignore_errors: true
  changed_when: false
  register: qemu_arm_registration_status

- name: Register qemu with docker
  when: qemu_arm_registration_status.rc != 0
  ansible.builtin.command:
    cmd: "docker run --rm --privileged multiarch/qemu-user-static --reset -p yes"


