---
- name: Check debian release codename
  command: lsb_release -c -s
  changed_when: false
  register: debian_release

- name: Ensure apt suite change from buster to oldstable has been accepted
  when: debian_release.stdout == "buster"
  block:
    - name: apt update ignoring failures
      ignore_errors: true
      become: true
      apt:
        update-cache: yes
        cache_valid_time: 3600
      register: apt_update_initial

    - name: Accept suite change and update if the update failed with suite change reason only
      become: true
      command: apt-get --allow-releaseinfo-change-suite update
      when: "(apt_update_initial.failed) and (apt_update_initial.msg == \"Failed to update apt cache: W:This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details., E:Repository 'http://security.debian.org buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable', W:This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details., W:Repository 'http://ftp.debian.org/debian buster InRelease' changed its 'Version' value from '10.7' to '10.11', E:Repository 'http://ftp.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable', W:This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details., E:Repository 'http://ftp.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates', W:This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details., E:Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'\")"

- name: apt update and upgrade
  become: true
  apt:
    upgrade: yes
    update-cache: yes
    cache_valid_time: 3600
 
- name: Install required packages
  become: true
  package: 
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git
    - vim
