---
- name: Add user eviljonny
  become: true
  ansible.builtin.user:
    name: eviljonny
    comment: Jonathan Harden
    state: present
    groups: sudo
    append: yes

- name: Configure eviljonny
  become: true
  become_user: eviljonny
  block:
    - name: Create ssh config directory
      ansible.builtin.file:
        path: /home/eviljonny/.ssh
        state: directory
        owner: eviljonny
        group: eviljonny
        mode: 0755

    - name: Add eviljonnys ssh public keys
      get_url:
        url: https://github.com/jfharden.keys
        dest: /home/eviljonny/.ssh/authorized_keys
        mode: '0640'
        owner: eviljonny
        group: eviljonny

- name: Allow sudo with no password for eviljonny
  become: true
  ansible.builtin.copy:
    dest: /etc/sudoers.d/010_eviljonny-nopasswd
    owner: root
    group: root
    mode: "0440"
    content: "eviljonny ALL=(ALL) NOPASSWD: ALL"
